public enum GameStates
{
    PLAYER0_DRAWING,
    PLAYER0_DISCARDING,
    PLAYER0_OFFERING,
    OPPONENT1_DRAWING,
    OPPONENT1_DISCARDING,
    OPPONENT1_OFFERING,
    OPPONENT2_DRAWING,
    OPPONENT2_DISCARDING,
    OPPONENT2_OFFERING,
    OPPONENT3_DRAWING,
    OPPONENT3_DISCARDING,
    OPPONENT3_OFFERING,
    PROCESSING,
}